FROM golang:1.23.0-alpine3.20 AS builder

RUN apk update && apk add bash

WORKDIR /app

COPY . .
COPY ./go.mod .
COPY ./go.sum .

RUN go mod download && \
    go build -o myapp ./cmd/main

FROM alpine:3.20

WORKDIR /app

RUN apk add --no-cache ca-certificates && \
    apk update && \
    apk upgrade && \
    rm -rf /var/cache/apk/*

COPY --from=builder /app/myapp .

CMD ["./myapp"]
